import {
  IsIn, IsNotEmpty, IsOptional, IsString, Length, MaxLength, MinLength,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

class DeviceDto {
  @ApiProperty({ description: 'Stable per-install id generated by the app' })
  @IsString() @Length(8, 64)
  deviceId: string;

  @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(80)
  deviceName?: string;

  @ApiPropertyOptional() @IsOptional() @IsIn(['ios', 'android', 'web'])
  platform?: string;
}

export class SignupDto extends DeviceDto {
  @ApiProperty({ example: 'Ahmed Khan' })
  @IsString() @IsNotEmpty() @MinLength(2) @MaxLength(80)
  name: string;

  @ApiProperty({ example: '0300 1234567', description: 'As typed; the server normalises to E.164' })
  @IsString() @IsNotEmpty() @MaxLength(32)
  phone: string;

  @ApiProperty({ example: 'PK', description: 'ISO country the phone number belongs to' })
  @IsString() @Length(2, 2)
  countryCode: string;

  @ApiProperty({ minLength: 8 })
  @IsString() @MaxLength(200)
  password: string;

  @ApiProperty({ enum: ['customer', 'worker'] })
  @IsIn(['customer', 'worker'])
  type: 'customer' | 'worker';

  @ApiPropertyOptional({ enum: ['en', 'ar', 'ur'] })
  @IsOptional() @IsIn(['en', 'ar', 'ur'])
  locale?: 'en' | 'ar' | 'ur';
}

export class LoginDto extends DeviceDto {
  @ApiProperty({ example: '0300 1234567' })
  @IsString() @IsNotEmpty() @MaxLength(32)
  phone: string;

  @ApiProperty({ example: 'PK' })
  @IsString() @Length(2, 2)
  countryCode: string;

  @ApiProperty()
  @IsString() @IsNotEmpty() @MaxLength(200)
  password: string;
}

export class AdminLoginDto extends DeviceDto {
  @ApiProperty() @IsString() @IsNotEmpty() @MaxLength(254)
  email: string;

  @ApiProperty() @IsString() @IsNotEmpty() @MaxLength(200)
  password: string;
}

export class RefreshDto {
  @ApiProperty() @IsString() @IsNotEmpty() @MaxLength(200)
  refreshToken: string;
}

export class ChangePasswordDto {
  @ApiProperty() @IsString() @IsNotEmpty() @MaxLength(200)
  currentPassword: string;

  @ApiProperty() @IsString() @MaxLength(200)
  newPassword: string;
}
