-- AlterTable
ALTER TABLE "ChangeOrder" ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'USD',
ALTER COLUMN "revisedPrice" SET DATA TYPE INTEGER USING ROUND("revisedPrice" * 100)::INTEGER;

-- AlterTable
ALTER TABLE "JobRequest" ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'USD',
ALTER COLUMN "paymentAmount" SET DATA TYPE INTEGER USING ROUND("paymentAmount" * 100)::INTEGER;

-- AlterTable
ALTER TABLE "Quote" ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'USD',
ALTER COLUMN "totalAmount" SET DATA TYPE INTEGER USING ROUND("totalAmount" * 100)::INTEGER;

-- AlterTable
ALTER TABLE "Service" ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'USD',
ALTER COLUMN "basePrice" SET DATA TYPE INTEGER USING ROUND("basePrice" * 100)::INTEGER;

-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "amount" SET DATA TYPE INTEGER USING ROUND("amount" * 100)::INTEGER;

-- AlterTable
ALTER TABLE "Worker" ADD COLUMN     "currency" TEXT NOT NULL DEFAULT 'USD',
ALTER COLUMN "minimumCallOutFee" SET DATA TYPE INTEGER USING ROUND("minimumCallOutFee" * 100)::INTEGER;

